### PR TITLE
Change the format of romanizing to MS-IME

### LINKED ISSUE #29: Fix romaji format
SudachiReadingFormFilter provides romanized pronunciations of tokens.  We use Kuromoji's module for it. Because the format of romanizing is odd (modified Hepburn system), it is not useful.

For example,
* コウ → kō
* シュウ → shū
* ロ゜→ lo

See
https://github.com/apache/lucene-solr/blob/master/lucene/analysis/kuromoji/src/java/org/apache/lucene/analysis/ja/util/ToStringUtil.java

Sometimes romanized pronunciations is used in narrowing with a incomplete query.  Kunrei system is better for such a task.

### PR DESCRIPTION
**Pull request by kazuma-t**
fix #29

### CODE REVIEW

**Comment by hiroshi-matsuda** [comment]
The codes are fine!
Should we consider transforming some Japanese symbols to ascii's ones?
If no, please merge this PR.

**Comment by kazuma-t** [comment]
For example?

**Comment by hiroshi-matsuda** [comment]
Wide-width versions of ()-/:;¥ and so on. I don't know whether these characters apper in reading field or not. If they appear, conversion to half-width may be needed.

**Comment by kazuma-t** [comment]
The system dictionaries include `、。，＝～™` as such characters. It is better to fix them than to convert them in this filter, I think. We will fix the dictionaries in the next release.

**Comment by kazuma-t** [comment]
Ah... It seems reasonable that readings fields include `・＝` in Japanese. We probably should drop them in this filter. I'll fix it.

**Comment by hiroshi-matsuda** [comment]
Okay. I'd merge this PR.

**Pull request merged**
